extends Resource
class_name Words

#const common_words: Array[String] = [
	#"the", "be", "to", "of", "and", "a", "in", "that", "have", "it", "for",
	#"not", "on", "with", "he", "as", "you", "do", "at", "this", "but", "his",
	#"by", "from", "they", "we", "say", "her", "she", "or", "an", "will", "my",
	#"one", "all", "would", "there", "their", "what", "so", "up", "out", "if",
	#"about", "who", "get", "which", "go", "me", "when", "make", "can", "like",
	#"time", "no", "just", "him", "know", "take", "people", "into", "year",
	#"your", "good", "some", "could", "them", "see", "other", "than", "then",
	#"now", "look", "only", "come", "its", "over", "think", "also", "back",
	#"after", "use", "two", "how", "our", "work", "first", "well", "way",
	#"even", "new", "want", "because", "any", "these", "give", "day", "most",
	#"us",
#]

const common_words: Array[String] = [
	"the", "be", "to", "of", "and", "a", "in", "that", "have", "it", "for",
	"not", "on", "with", "he", "as", "you", "do", "at", "this", "but", "his",
	"by", "from", "they", "we", "say", "her", "she", "or", "an", "will", "my",
	"one", "all", "would", "there", "their", "what", "so", "up", "out", "if",
	"about", "who", "get", "which", "go", "me", "when", "make", "can", "like",
	"time", "no", "just", "him", "know", "take", "people", "into", "year",
	"your", "good", "some", "could", "them", "see", "other", "than", "then",
	"now", "look", "only", "come", "its", "over", "think", "also", "back",
	"after", "use", "two", "how", "our", "work", "first", "well", "way",
	"even", "new", "want", "because", "any", "these", "give", "day", "most",
	"us", "where", "down", "only", "long", "man", "come", "find", "here",
	"much", "about", "world", "through", "get", "very", "just", "must", "much",
	"did", "back", "right", "any", "good", "every", "more", "say", "should",
	"think", "well", "down", "never", "always", "something", "without", "before",
	"between", "through", "really", "family", "story", "life", "children", "side",
	"next", "little", "right", "house", "hand", "high", "home", "place", "while",
	"where", "after", "last", "long", "old", "came", "call", "away", "help",
	"great", "still", "small", "move", "much", "must", "show", "tell", "turn",
	"walk", "word", "around", "another", "begin", "each", "feel", "great", "group",
	"leave", "might", "part", "point", "program", "seem", "system", "though",
	"three", "today", "under", "where", "why", "write", "across", "begin", "close",
	"develop", "early", "example", "face", "fact", "feel", "game", "govern", "happen",
	"hold", "information", "keep", "large", "less", "level", "local", "main",
	"member", "money", "morning", "name", "national", "order", "own", "parent",
	"place", "problem", "put", "question", "report", "result", "right", "room",
	"school", "service", "set", "several", "small", "state", "study", "such",
	"take", "system", "though", "through", "today", "together", "told", "total",
	"town", "train", "tree", "true", "turn", "type", "under", "until", "upon",
	"value", "various", "very", "view", "voice", "wait", "want", "watch", "water",
	"week", "white", "whole", "woman", "wonder", "work", "world", "would",
	"year", "young", "able", "above", "add", "almost", "along", "also",
	"among", "amount", "animal", "appear", "area", "arm", "around", "ask",
	"away", "ball", "bank", "base", "bear", "beat", "beauty", "bed", "behind",
	"best", "better", "board", "body", "book", "both", "box", "boy", "bring",
	"build", "build", "call", "care", "carry", "case", "catch", "cause",
	"central", "certain", "change", "character", "check", "child", "choice",
	"choose", "church", "city", "class", "clear", "clear", "close", "cold",
	"collect", "color", "come", "common", "company", "compare", "complete",
	"concern", "condition", "consider", "control", "cost", "country", "course",
	"court", "cover", "create", "crime", "cut", "dark", "data", "deal", "death",
	"decide", "deep", "degree", "depend", "develop", "die", "differ", "difficult",
	"direct", "discuss", "display", "distance", "district", "divide", "doctor",
	"door", "down", "draw", "dream", "drive", "drop", "during", "each", "early",
	"east", "easy", "eat", "economy", "edge", "education", "effect", "effort",
	"eight", "either", "element", "else", "end", "enjoy", "enough", "enter",
	"entire", "environment", "equal", "especially", "even", "evening", "event",
	"ever", "every", "everyone", "exact", "example", "exist", "expect",
	"explain", "express", "extra", "eye", "face", "fact", "fall", "family",
	"far", "fast", "father", "fear", "feature", "feel", "field", "fight",
	"figure", "fill", "final", "fine", "finish", "fire", "firm", "fish", "five",
	"floor", "fly", "focus", "follow", "food", "foot", "force", "form",
	"forward", "free", "friend", "front", "full", "future", "game", "garden",
	"gas", "general", "generate", "get", "girl", "give", "glass", "go", "goal",
	"good", "govern", "great", "green", "ground", "group", "grow", "growth",
	"guess", "half", "hand", "hang", "happen", "hard", "have", "head", "health",
	"hear", "heart", "heat", "heavy", "help", "here", "high", "hold", "home",
	"hope", "hospital", "hot", "hotel", "hour", "house", "how", "however",
	"huge", "human", "hundred", "husband", "idea", "imagine", "impact",
	"improve", "include", "increase", "indeed", "indicate", "individual",
	"industry", "inform", "inside", "instead", "interest", "internal",
	"issue", "item", "join", "joy", "judge", "keep", "key", "kill", "kind",
	"know", "land", "language", "large", "last", "late", "later", "laugh",
	"lead", "leader", "learn", "least", "leave", "left", "legal", "less",
	"letter", "level", "lie", "life", "light", "like", "likely", "line",
	"list", "listen", "little", "live", "local", "long", "look", "lose",
	"loss", "love", "low", "main", "major", "make", "manage", "many", "market",
	"marry", "match", "material", "matter", "may", "maybe", "mean", "measure",
	"media", "meet", "meeting", "member", "memory", "mention", "message",
	"method", "middle", "might", "mile", "military", "million", "mind",
	"minute", "miss", "model", "money", "month", "more", "morning", "most",
	"mother", "move", "much", "music", "must", "name", "nation", "national",
	"natural", "nature", "near", "nearly", "necessary", "need", "network",
	"never", "new", "news", "next", "nice", "night", "none", "north", "note",
	"nothing", "notice", "number", "occur", "offer", "office", "often", "old",
	"once", "one", "only", "open", "operate", "opinion", "opportunity",
	"option", "order", "organize", "other", "outside", "over", "own", "page",
	"pain", "paint", "paper", "parent", "park", "part", "particular",
	"partner", "party", "pass", "past", "patient", "pattern", "pay", "peace",
	"people", "perform", "perhaps", "period", "person", "personal", "phone",
	"physical", "picture", "piece", "place", "plan", "plant", "play", "player",
	"point", "police", "policy", "political", "power", "practice", "prepare",
	"present", "president", "pressure", "pretty", "prevent", "price", "print",
	"private", "probably", "process", "produce", "product", "program",
	"project", "proper", "property", "protect", "provide", "public", "pull",
	"purpose", "push", "quality", "question", "quick", "quiet", "quite",
	"radio", "raise", "range", "rate", "rather", "reach", "read", "ready",
	"real", "realize", "really", "reason", "receive", "recent", "recognize",
	"record", "red", "reduce", "reflect", "region", "relate", "release",
	"remain", "remember", "remove", "report", "represent", "require",
	"research", "resource", "respond", "response", "rest", "result", "return",
	"reveal", "rich", "right", "rise", "risk", "road", "rock", "role", "room",
	"rule", "run", "safe", "same", "save", "say", "scene", "school", "science",
	"score", "sea", "season", "seat", "second", "section", "security", "see",
	"seek", "seem", "sell", "send", "sense", "series", "serious", "serve",
	"service", "set", "settle", "seven", "several", "shake", "share", "she",
	"shoot", "short", "should", "shoulder", "show", "side", "sign", "simple",
	"simply", "since", "sing", "single", "sister", "sit", "site", "six", "size",
	"sleep", "small", "smile", "social", "society", "some", "someone",
	"something", "sometimes", "son", "song", "soon", "sort", "sound", "south",
	"space", "speak", "special", "specific", "spend", "sport", "spring",
	"staff", "stage", "stand", "standard", "star", "start", "state", "station",
	"stay", "step", "still", "stock", "stop", "store", "story", "straight",
	"strategy", "street", "strong", "structure", "student", "study", "stuff",
	"style", "subject", "success", "such", "sudden", "suffer", "suggest",
	"summer", "support", "sure", "system", "table", "take", "talk", "task",
	"tax", "teach", "teacher", "team", "technology", "television", "tell",
	"ten", "tend", "term", "test", "than", "thank", "that", "the", "their",
	"them", "then", "there", "therefore", "these", "they", "thing", "think",
	"third", "this", "those", "though", "thought", "thousand", "three",
	"through", "throw", "thus", "time", "to", "today", "together", "told",
	"too", "top", "total", "touch", "toward", "town", "trade", "traditional",
	"training", "travel", "treat", "treatment", "tree", "trial", "trip", "true",
	"truth", "try", "turn", "type", "under", "understand", "unit", "until",
	"up", "upon", "us", "use", "usual", "value", "various", "very", "victim",
	"view", "visit", "voice", "vote", "wait", "walk", "wall", "want", "war",
	"watch", "water", "way", "we", "weapon", "wear", "weather", "week", "weight",
	"well", "west", "what", "whatever", "when", "where", "whether", "which",
	"while", "white", "who", "whole", "whom", "whose", "why", "wide", "wife",
	"will", "win", "wind", "window", "wish", "with", "within", "without",
	"woman", "wonder", "word", "work", "worker", "world", "worry", "would",
	"write", "writer", "wrong", "yard", "yeah", "year", "yes", "yet", "you",
	"young", "your", "yourself", "zone"
]
